server:
  port : 8880

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: guest-service
          uri: lb://GUEST-SERVICE
          predicates:
            - Path=/guests/**
        - id: room-service
          uri: lb://ROOM-SERVICE
          predicates:
            - Path=/rooms/**
            - Path=/room-categories/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
