server:
  port : 8880

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: guest-service
          uri: http://localhost:8088
          predicates:
            - Path=/guests/**
        - id: room-service
          uri: http://localhost:8090
          predicates:
            - Path=/rooms/**
            - Path=/room-categories/**
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true